image := "localhost/fcos-k3s"
base := "quay.io/trusted-execution-clusters/fcos@shasum5a906c7fb2b17deb1f78c6aaf663c9770fddb2e99a2fe70e59148f5c4509bbb8"
archive := "fcos.ociarchive"
kv-image := "quay.io/afrosi_rh/fedora-coreos-kubevirt:demo"

build:
    sudo podman build --network=host --no-cache --build-arg BASE={{base}} -t {{image}} -f Containerfile .

oci-archive:
    sudo skopeo copy containers-storage:{{image}} oci-archive:{{archive}}

cosa_function := '''
    #!/usr/bin/env bash
    cosa() {
        env | grep COREOS_ASSEMBLER || true

        # Default container image
        COREOS_ASSEMBLER_CONTAINER_LATEST="quay.io/coreos-assembler/coreos-assembler:latest"
        sudo podman pull $COREOS_ASSEMBLER_CONTAINER_LATEST

        set -ex
        sudo podman run --rm -ti --security-opt=label=disable --privileged -u 0 \
				--network host \
            -v=${PWD}:/srv/ --device=/dev/kvm --device=/dev/fuse \
            --tmpfs=/tmp -v=/var/tmp:/var/tmp --name=cosa \
            ${COREOS_ASSEMBLER_CONFIG_GIT:+-v=$COREOS_ASSEMBLER_CONFIG_GIT:/srv/src/config/:ro} \
            ${COREOS_ASSEMBLER_GIT:+-v=$COREOS_ASSEMBLER_GIT/src/:/usr/lib/coreos-assembler/:ro} \
            ${COREOS_ASSEMBLER_ADD_CERTS:+-v=/etc/pki/ca-trust:/etc/pki/ca-trust:ro} \
            ${COREOS_ASSEMBLER_CONTAINER_RUNTIME_ARGS} \
            ${COREOS_ASSEMBLER_CONTAINER:-$COREOS_ASSEMBLER_CONTAINER_LATEST} "$@"
    }
'''

kubevirt:
    #!/usr/bin/env bash
    {{cosa_function}}
    rm -rf cache
    mkdir -p cache
    cp {{archive}} cache/{{archive}}
    cd cache
    cosa init --force https://github.com/coreos/fedora-coreos-config
    cosa import oci-archive:/srv/{{archive}}
    cosa osbuild kubevirt

qemu:
    #!/usr/bin/env bash
    {{cosa_function}}
    rm -rf cache
    mkdir -p cache
    cosa init --force https://github.com/coreos/fedora-coreos-config
    cosa import oci-archive:/srv/{{archive}}
    cosa osbuild qemu

push-kubevirt:
	#!/usr/bin/env bash
	image=$(ls cache/builds/latest/x86_64/fedora-coreos-*-kubevirt.x86_64.ociarchive)
	skopeo copy oci-archive:$image containers-storage:{{kv-image}}
	echo "Pushing image {{kv-image}}"
	podman push {{kv-image}}
