apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vmconf
spec:
  runStrategy: Always
  template:
    metadata:
    spec:
      domain:
        cpu:
          model: "EPYC-v4"
        launchSecurity:
          snp: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          tpm:
            persistent: true
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          rng: {}
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: containerdisk
        containerDisk:
          image: "quay.io/afrosi_rh/fedora-coreos-kubevirt:demo"
          imagePullPolicy: Always
      - name: cloudinitdisk
        cloudInitConfigDrive:
          secretRef:
            name: vm-ign-conf
